#
# Copyright (c) 2017, 2020 ADLINK Technology Inc.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
#
# Contributors:
#   ADLINK zenoh team, <zenoh@adlink-labs.tech>
#
name: Rust

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  schedule:
    - cron: "0 6 * * 1-5"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest] # Note: windows not supported because of cyclocut not ported

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          components: rustfmt, clippy

      - name: zplugin-dds > Code format check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path zplugin-dds/Cargo.toml -- --check

      - name: zplugin-dds > Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path zplugin-dds/Cargo.toml --all --examples -- -D warnings

      - name: zplugin-dds > Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path zplugin-dds/Cargo.toml --verbose --all-targets

      - name: zplugin-dds > Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path zplugin-dds/Cargo.toml --verbose

      - name: zenoh-bridge-dds > Code format check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path zenoh-bridge-dds/Cargo.toml -- --check

      - name: zenoh-bridge-dds > Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path zenoh-bridge-dds/Cargo.toml --all --examples -- -D warnings

      - name: zenoh-bridge-dds > Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path zenoh-bridge-dds/Cargo.toml --verbose --all-targets

      - name: zenoh-bridge-dds > Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path zenoh-bridge-dds/Cargo.toml --verbose
